### ISSUE TITLE
Wrong ad prefab search filter if there are other assets with a similar name

### ISSUE THREAD

**Issue by EraCat2** [appodeal/appodeal-unity-plugin-upm#19]
Hi guys! 
I ran into an SDK initialization issue when trying to test ads in the Unity editor.
I have a script named "RewardedAdManager" and DummyAppodealClient finds this script and tries to use it as an ad and I get an error.

https://github.com/appodeal/appodeal-unity-plugin-upm/blob/4c9c09738284b39a5d78bdb380e8163474f2e050/Runtime/Platforms/Monetization/Dummy/DummyAppodealClient.cs#L219

I suggest adding an explicit asset type to the filter string:
```
var assetGuids = AssetDatabase.FindAssets(prefabName + " t:prefab");
```
It helps for me.

Perhaps you should mention this behavior somewhere, because it's not obvious that you shouldn't have assets with names similar to your prefab's name)
Thank you!

**Comment by DmitriiFeshchenko** [comment]
@EraCat2, hi. Thanks for your suggestions!

I [already renamed](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/8ced73695557849bae19f9892902a6a673a6036a) those files to minimize the risk of having other assets with similar names. This change will be included in v3.1.x release which should hopefully be published in 1-2 weeks.

I like your idea to use a type filter when finding test ad assets. I added this task to my backlog.
