### ISSUE TITLE
Can't install pods

### ISSUE THREAD

**Issue by Lucasito** [appodeal/appodeal-unity-plugin-upm#62]
- Computer OS: macOS
 - Unity Editor Version: 2022.3.21
 - Appodeal Unity Plugin Version: 3.3.0
 - Xcode Version: 15.3
 - CocoaPods Version: 1.15.2
 - 
I installed the new version of Appodeal 3.3.0 according to the instructions. Now the project is not built on iOS, When installing pods it writes a bunch of errors of incompatible versions. I specifically checked, you do have such problems in your repository. What am I doing wrong? I'm attaching the errors

pod install --repo-update

Error logs
[logs.txt](https://github.com/appodeal/appodeal-unity-plugin-upm/files/15373427/logs.txt)

pod file 
[Podfile.txt](https://github.com/appodeal/appodeal-unity-plugin-upm/files/15373426/Podfile.txt)

**Comment by Khrolovich** [comment]
Hi @Lucasito,

Appodeal SDK 3.3.0 requires a newer iOS Firebase version (~> 10.22) that corresponds to Firebase Unity SDK 11.8 
I checked with the Firebase Unity SDK 11.8.1 version and it works.
