### ISSUE TITLE
 Duplicate symbols

### ISSUE THREAD

**Issue by al1472av** [appodeal/appodeal-unity-plugin-upm#69]
- Computer OS: macOS
 - Unity Editor Version: 2021.3.36
 - Appodeal Unity Plugin Version: 3.3.2
 - Xcode Version: 15.4

## iOS build error in XCode
I get an error during the build process: 
"123 duplicate symbols" and "Linker command failed with exit code 1 (use -v to see invocation)". 

GPT told me that i can find list of duplicated symbols with "grep "duplicate symbol" build.log", so here is result of it:

duplicate symbol '_AppodealInitialize' in:
duplicate symbol '_AppodealSetBannerDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidFinishCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialDidDismissCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialDidClickCallback' in:
duplicate symbol '_AppodealSetInitializationDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidClickCallback' in:
duplicate symbol '_AppodealSetRewardedVideoDelegate' in:
duplicate symbol '__Z19CityHash128WithSeedPKcmNSt3__14pairIyyEE' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealBannerViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidFailToPresentCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidExpiredCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealInitializationDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealUnityMrecView._onScreen' in:
duplicate symbol '_OBJC_CLASS_$_AppodealAdRevenueDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialDidFailToLoadAdCallback' in:
duplicate symbol '_OBJC_CLASS_$_AppodealUnityMrecView' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidExpireCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidFailToPresentCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidLoadAdCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealAdRevenueDelegate._adRevenueReceivedCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidExpiredCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidFailToLoadAdCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidClickCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._touchIgnoresView' in:
duplicate symbol '_RootViewControllerUnityBannerView' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidShowCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoWillDismissCallback' in:
duplicate symbol '_OBJC_CLASS_$_AppodealInterstitialDelegate' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealInterstitialDelegate' in:
duplicate symbol '_OBJC_CLASS_$_AppodealBannerDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._ignoresTouchViews' in:
duplicate symbol '__Z10CityHash32PKcm' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidExpiredCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidFailToPresentCallback' in:
duplicate symbol '_AppodealSetInterstitialDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealUnityBannerView._onScreen' in:
duplicate symbol '_AppodealShowAd' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidFailToLoadAdCallback' in:
duplicate symbol '__Z18CityHash64WithSeedPKcmy' in:
duplicate symbol '_OBJC_CLASS_$_AppodealRewardedVideoDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialWillPresentCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealBannerDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialDidFailToPresentCallback' in:
duplicate symbol '__Z19CityHash64WithSeedsPKcmyy' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialDidLoadCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidFailToLoadAdCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealAdRevenueDelegate' in:
duplicate symbol '__Z11CityHash128PKcm' in:
duplicate symbol '__Z10CityHash64PKcm' in:
duplicate symbol '_OBJC_CLASS_$_AppodealMrecViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealUnityMrecView._mrecView' in:
duplicate symbol '_OBJC_CLASS_$_AppodealInitializationDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidPresentCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealUnityMrecView' in:
duplicate symbol '_AppodealSetLogLevel' in:
duplicate symbol '_RootViewController' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidShowCallback' in:
duplicate symbol '_AppodealSetMrecViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidReceiveTapActionCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInterstitialDelegate._interstitialsDidExpiredCallback' in:
duplicate symbol '_OBJC_CLASS_$_AppodealBannerViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealUnityBannerView._tabletBanner' in:
duplicate symbol '_AppodealSetBannerViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidLoadAdCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealMrecViewDelegate._mrecViewDidClickCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealUnityBannerView' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidFailToPresentCallback' in:
duplicate symbol '_OBJC_CLASS_$_AppodealUnityBannerView' in:
duplicate symbol '_OBJC_IVAR_$_AppodealUnityBannerView._bannerView' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._bannerViewDidLoadAdCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealMrecViewDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidLoadAdCallback' in:
duplicate symbol '_OBJC_METACLASS_$_AppodealRewardedVideoDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealRewardedVideoDelegate._rewardedVideoDidFailToLoadAdCallback' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerDelegate._bannerDidShowCallback' in:
duplicate symbol '_RootViewControllerUnityMrec' in:
duplicate symbol '_AppodealSetAdRevenueDelegate' in:
duplicate symbol '_OBJC_IVAR_$_AppodealBannerViewDelegate._touchIgnoresView' in:
duplicate symbol '_AppodealIsReadyWithStyle' in:
duplicate symbol '_OBJC_IVAR_$_AppodealInitializationDelegate._initializationCompletedCallback' in:
ld: 123 duplicate symbols

## Screenshots
![image](https://github.com/user-attachments/assets/d07bb3ff-c936-4fa4-a804-28dc84f2c206)
![image](https://github.com/user-attachments/assets/c80ec5ad-a85c-4bfa-80a8-cb1592eea217)

**Comment by Khrolovich** [comment]
Hello al1472av,

It looks like the manual plugin hadn’t been completely deleted. Try to delete Appodeal SDK using the “Appodeal” -> “Remove plugin” and manually delete the Appodeal directory from the Assets/Plugins/iOS if it is still there. 
Install the UPM-plugin from scratch. Check if all steps from the [integration guide](https://docs.appodeal.com/unity/get-started?distribution=upm) are done.

Feel free to contact our support team at [support@appodeal.com](mailto:support@appodeal.com) if you have any questions
