### ISSUE TITLE
Fire OS (Amazon): Interstitial ad plays for the same duration as a Rewarded video and cannot be skipped

### ISSUE THREAD

**Issue by NilConstantin** [appodeal/appodeal-unity-plugin-upm#73]
## Step 1: Environment

 - Computer OS: Windows
 - Unity Editor Version: 2021.3.29f1
 - Appodeal Unity Plugin Version: 3.2.0 and looks like upper
 
 - Target OS: Fire OS (Amazon device)
 - Bug Repro Rate: 100%* Maybe it's depends on ad-network, but I have problem with every ad.

## Step 2: Bug description
When showing an interstitial ad, a timer appears (although in rewarded ads, the timer is usually hidden). 
But instead of the usual 5 seconds, the timer lasts around 30 seconds on average — roughly the full length of a rewarded video. 
You **cannot** skip ad after 5 seconds.

It was OK on version 3.0.2.

## Step 3: How to reproduce
Step 1: Install Appodeal
Step 2: Remove all networks (except IAB) and all Services for platforms (iOS and Android) (not sure maybe it's optional step)
Step 3: Call Appodeal.Show(AppodealShowStyle.Interstitial) from application running on an amazon device.

## Step 4: Expected behavior
Expected: Ad with timer 5 seconds. 

## Step 5: Video
https://drive.google.com/file/d/11Y5_bGrwyn2GDFVL8TgX9i9sJLohuCGB/view?usp=sharing

## Step 6: Additional context
English is not my native language so sorry for it :)

**Comment by Khrolovich** [comment]
Hello @NilConstantin,

Based on your note that all networks except IAB have been removed, it’s likely that your case is related to Ad Server.

If you are using video ad creatives in Ad Server campaigns, please note that for Appodeal SDK version 3.2.0 and above, the countdown duration to the close button corresponds to the length of the uploaded video.

As a potential solution, I would recommend either replacing the video ad creatives with shorter ones or opting for image-based ad creatives in your Ad Server campaigns.
